apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-service
  namespace: nexusplay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leaderboard-service
  template:
    metadata:
      labels:
        app: leaderboard-service
    spec:
      containers:
        - name: leaderboard-service
          image: yazmhog/nexusplay-leaderboard-service:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis.nexusplay.svc.cluster.local:6379
            - name: PGHOST
              value: postgres.nexusplay.svc.cluster.local
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
