apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: game-service
  namespace: nexusplay
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: game-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: leaderboard-service
  namespace: nexusplay
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: leaderboard-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
