apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: nexusplay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
        - name: game-service
          image: yazmhog/nexusplay-game-service:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis.nexusplay.svc.cluster.local:6379
            - name: LEADERBOARD_URL
              value: http://leaderboard-service.nexusplay.svc.cluster.local:3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
